// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjpwxhvakqdxuiicpkjj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqcHd4aHZha3FkeHVpaWNwa2pqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNTI1NzMsImV4cCI6MjA2MDcyODU3M30.9dv2nhBfhaN7iYFQXGBhdzMLHSYeKaiX1MpdfSzXXbo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);